
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package visualbasiccompilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_EQUALS = 36;
  public static final int TK_MINUS = 24;
  public static final int TK_GREATERTHAN = 32;
  public static final int TK_WRITE = 46;
  public static final int TK_PRODUCT = 25;
  public static final int TK_LESSEQUAL = 35;
  public static final int TK_FOR = 11;
  public static final int TK_LESSTHAN = 33;
  public static final int TK_NOT = 30;
  public static final int TK_AND = 28;
  public static final int TK_COMMA = 40;
  public static final int TK_OR = 29;
  public static final int TK_UNTIL = 15;
  public static final int TK_AMPERSAND = 27;
  public static final int TK_ELSEIF = 9;
  public static final int TK_IF = 7;
  public static final int TK_ID = 49;
  public static final int TK_PAROUT = 39;
  public static final int TK_BYVAL = 5;
  public static final int TK_BOOLEAN = 3;
  public static final int TK_DIM = 41;
  public static final int TK_GREATEREQUAL = 34;
  public static final int TK_EXIT = 44;
  public static final int TK_LOOP = 13;
  public static final int TK_NEXT = 16;
  public static final int TK_STRINGVAL = 48;
  public static final int TK_RETURN = 45;
  public static final int TK_TRUE = 18;
  public static final int TK_PARIN = 38;
  public static final int TK_NUMBER = 50;
  public static final int EOF = 0;
  public static final int TK_BYREF = 6;
  public static final int error = 1;
  public static final int TK_STRUCTURE = 22;
  public static final int TK_TO = 12;
  public static final int TK_WHILE = 14;
  public static final int TK_ELSE = 10;
  public static final int TK_READ = 47;
  public static final int TK_DIVISION = 26;
  public static final int TK_END = 43;
  public static final int TK_SUM = 23;
  public static final int TK_FALSE = 19;
  public static final int TK_AS = 42;
  public static final int TK_THEN = 8;
  public static final int TK_STRING = 4;
  public static final int TK_FUNCTION = 20;
  public static final int TK_DO = 17;
  public static final int TK_SUB = 21;
  public static final int TK_NOTEQUAL = 37;
  public static final int TK_INTEGER = 2;
  public static final int TK_XOR = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_INTEGER",
  "TK_BOOLEAN",
  "TK_STRING",
  "TK_BYVAL",
  "TK_BYREF",
  "TK_IF",
  "TK_THEN",
  "TK_ELSEIF",
  "TK_ELSE",
  "TK_FOR",
  "TK_TO",
  "TK_LOOP",
  "TK_WHILE",
  "TK_UNTIL",
  "TK_NEXT",
  "TK_DO",
  "TK_TRUE",
  "TK_FALSE",
  "TK_FUNCTION",
  "TK_SUB",
  "TK_STRUCTURE",
  "TK_SUM",
  "TK_MINUS",
  "TK_PRODUCT",
  "TK_DIVISION",
  "TK_AMPERSAND",
  "TK_AND",
  "TK_OR",
  "TK_NOT",
  "TK_XOR",
  "TK_GREATERTHAN",
  "TK_LESSTHAN",
  "TK_GREATEREQUAL",
  "TK_LESSEQUAL",
  "TK_EQUALS",
  "TK_NOTEQUAL",
  "TK_PARIN",
  "TK_PAROUT",
  "TK_COMMA",
  "TK_DIM",
  "TK_AS",
  "TK_END",
  "TK_EXIT",
  "TK_RETURN",
  "TK_WRITE",
  "TK_READ",
  "TK_STRINGVAL",
  "TK_ID",
  "TK_NUMBER"
  };
}

